WITH statcast AS (
    SELECT * FROM {{ ref('stg_statcast') }}
)

SELECT
    ---------- primary
    unique_key,
    game_id,
    game_pa_number,
    pa_pitch_number,
    game_date,
    home_team,
    away_team,
    pitch_result_desc,
    gameday_desc,
    pa_event,

    ---------- primary
    batter_id,
    pitcher_id,
    fielder_2_id,
    fielder_3_id,
    fielder_4_id,
    fielder_5_id,
    fielder_6_id,
    fielder_7_id,
    fielder_8_id,
    fielder_9_id,
    on_1b_id,
    on_2b_id,
    on_3b_id,

    ---------- attributes
    season,
    game_type,
    inning,
    inning_topbot,
    outs,
    balls,
    strikes,
    home_score,
    away_score,
    home_score_diff,
    post_home_score,
    post_away_score,
    bat_score,
    fld_score,
    bat_score_diff,
    post_bat_score,
    post_fld_score,
    pitcher_throws,
    age_pit,
    age_pit_legacy,
    n_thruorder_pitcher,
    pitcher_days_since_prev_game,
    pitcher_days_until_next_game,
    batter_stands,
    age_bat,
    age_bat_legacy,
    sz_top,
    sz_bot,
    n_priorpa_thisgame_player_at_bat,
    batter_days_since_prev_game,
    batter_days_until_next_game,
    pitch_name,
    pitch_type,
    release_speed,
    release_pos_x,
    release_pos_y,
    release_pos_z,
    release_spin_rate,
    release_extension,
    effective_speed,
    vx0,
    vy0,
    vz0,
    ax,
    ay,
    az,
    pfx_x,
    pfx_z,
    plate_x,
    plate_z,
    arm_angle,
    api_break_x_arm,
    api_break_x_batter_in,
    api_break_z_with_gravity,
    spin_axis,
    zone_loc,
    pitch_result,
    bat_speed,
    swing_length,
    miss_distance,
    hyper_speed,
    attack_angle,
    attack_direction,
    swing_path_tilt,
    intercept_ball_minus_batter_pos_x_inches,
    intercept_ball_minus_batter_pos_y_inches,
    bb_type,
    hit_location,
    hc_x,
    hc_y,

    ROUND(
        ATAN(
            (hc_x - 125.42)
            / (198.27 - hc_y)
        )
        * 180
        / PI()
        * 0.75,

        2
    )::DECIMAL(18, 2)
        AS spray_angle,

    hit_distance_sc,
    launch_speed,
    launch_angle,
    estimated_ba_using_speedangle,
    estimated_slg_using_speedangle,
    estimated_woba_using_speedangle,
    launch_speed_angle_type,
    if_fielding_alignment,
    of_fielding_alignment,
    woba_value,
    woba_denom,
    babip_value,
    iso_value,
    home_win_exp,
    bat_win_exp,
    delta_home_win_exp,
    delta_run_exp,
    delta_pitcher_run_exp,
    sv_id,
    is_pa_event

FROM statcast
