WITH source AS (
    SELECT * FROM {{ source('raw', 'retrosheet_plays') }}
)

SELECT
    {{ dbt_utils.generate_surrogate_key(['gid', 'pn']) }} AS unique_key,

    gid                                                   AS game_id,
    event,
    inning,
    top_bot,
    vis_home,
    site                                                  AS park_id,
    batteam                                               AS bat_team_id,
    pitteam                                               AS pitch_team_id,
    score_v                                               AS score_vis,
    score_h                                               AS score_home,
    batter                                                AS batter_id,
    pitcher                                               AS pitcher_id,
    lp                                                    AS batter_lpos,
    bat_f                                                 AS batter_fpos,
    bathand                                               AS batter_hand,
    pithand                                               AS pitcher_hand,
    balls,
    strikes,
    count,
    pitches,
    nump                                                  AS pa_pitches,
    pa,
    ab,
    single,
    double,
    triple,
    hr,
    sh,
    sf,
    hbp,
    walk,
    k,
    xi,
    roe,
    fc,
    othout                                                AS other_out,
    noout                                                 AS no_out,
    oth                                                   AS other_plus_no_out,
    bip,
    bunt,
    ground,
    fly,
    line,
    iw,
    gdp,
    othdp                                                 AS other_dp,
    tp,
    fle,
    wp,
    pb,
    bk,
    oa,
    di,
    sb2,
    sb3,
    sbh,
    cs2,
    cs3,
    csh,
    pko1,
    pko2,
    pko3,
    k_safe,
    e1,
    e2,
    e3,
    e4,
    e5,
    e6,
    e7,
    e8,
    e9,
    outs_pre,
    outs_post,
    br1_pre                                               AS br1_pre_player_id,
    br2_pre                                               AS br2_pre_player_id,
    br3_pre                                               AS br3_pre_player_id,
    br1_post                                              AS br1_post_player_id,
    br2_post                                              AS br2_post_player_id,
    br3_post                                              AS br3_post_player_id,
    lob_id1                                               AS lob1_player_id,
    lob_id2                                               AS lob2_player_id,
    lob_id3                                               AS lob3_player_id,
    pr1_pre                                               AS pr1_pre_player_id,
    pr2_pre                                               AS pr2_pre_player_id,
    pr3_pre                                               AS pr3_pre_player_id,
    pr1_post                                              AS pr1_post_player_id,
    pr2_post                                              AS pr2_post_player_id,
    pr3_post                                              AS pr3_post_player_id,
    run_b                                                 AS run_b_player_id,
    run1                                                  AS run1_player_id,
    run2                                                  AS run2_player_id,
    run3                                                  AS run3_player_id,
    prun_b                                                AS prun_b_player_id,
    prun1                                                 AS prun1_player_id,
    prun2                                                 AS prun2_player_id,
    prun3                                                 AS prun3_player_id,
    ur_b,
    ur1,
    ur2,
    ur3,
    rbi_b,
    rbi1,
    rbi2,
    rbi3,
    runs,
    rbi,
    er,
    tur,
    l1                                                    AS l1_player_id,
    l2                                                    AS l2_player_id,
    l3                                                    AS l3_player_id,
    l4                                                    AS l4_player_id,
    l5                                                    AS l5_player_id,
    l6                                                    AS l6_player_id,
    l7                                                    AS l7_player_id,
    l8                                                    AS l8_player_id,
    l9                                                    AS l9_player_id,
    lf1                                                   AS l1_fpos,
    lf2                                                   AS l2_fpos,
    lf3                                                   AS l3_fpos,
    lf4                                                   AS l4_fpos,
    lf5                                                   AS l5_fpos,
    lf6                                                   AS l6_fpos,
    lf7                                                   AS l7_fpos,
    lf8                                                   AS l8_fpos,
    lf9                                                   AS l9_fpos,
    f2                                                    AS f2_player_id,
    f3                                                    AS f3_player_id,
    f4                                                    AS f4_player_id,
    f5                                                    AS f5_player_id,
    f6                                                    AS f6_player_id,
    f7                                                    AS f7_player_id,
    f8                                                    AS f8_player_id,
    f9                                                    AS f9_player_id,
    po0,
    po1,
    po2,
    po3,
    po4,
    po5,
    po6,
    po7,
    po8,
    po9,
    a1,
    a2,
    a3,
    a4,
    a5,
    a6,
    a7,
    a8,
    a9,
    fseq,
    batout1                                               AS bat_out1_player_id,
    batout2                                               AS bat_out2_player_id,
    batout3                                               AS bat_out3_player_id,
    brout_b                                               AS br_out_b_player_id,
    brout1                                                AS br_out1_player_id,
    brout2                                                AS br_out2_player_id,
    brout3                                                AS br_out3_player_id,
    firstf                                                AS first_fpos,
    loc,
    hittype                                               AS hit_type,
    dpopp                                                 AS dp_opp,
    "pivot"                                               AS dp_pivot,
    pn                                                    AS play_number,
    umphome                                               AS ump_home_id,
    ump1b                                                 AS ump_1b_id,
    ump2b                                                 AS ump_2b_id,
    ump3b                                                 AS ump_3b_id,
    umplf                                                 AS ump_lf_id,
    umprf                                                 AS ump_rf_id,
    date                                                  AS game_date,
    gametype                                              AS game_type,
    pbp                                                   AS pbp_source

FROM source
