import duckdb
import requests

from pathlib import Path
from zipfile import ZipFile

from baseball_db.constants import DATABASE_NAME


class Retrosheet:
    """Extract and load Retrosheet data.
    https://www.retrosheet.org/downloads/csvcontents.html
    """
    ALLPLAYERS_FIELD_DTYPES = {
        'id': 'VARCHAR',
        'last': 'VARCHAR',
        'first': 'VARCHAR',
        'bat': 'VARCHAR',
        'throw': 'VARCHAR',
        'team': 'VARCHAR',
        'g': 'USMALLINT',
        'g_p': 'USMALLINT',
        'g_sp': 'USMALLINT',
        'g_rp': 'USMALLINT',
        'g_c': 'USMALLINT',
        'g_1b': 'USMALLINT',
        'g_2b': 'USMALLINT',
        'g_3b': 'USMALLINT',
        'g_ss': 'USMALLINT',
        'g_lf': 'USMALLINT',
        'g_cf': 'USMALLINT',
        'g_rf': 'USMALLINT',
        'g_of': 'USMALLINT',
        'g_dh': 'USMALLINT',
        'g_ph': 'USMALLINT',
        'g_pr': 'USMALLINT',
        'first_g': 'VARCHAR',
        'last_g': 'VARCHAR',
        'season': 'USMALLINT'
    }

    BALLPARKS_FIELD_DTYPES = {
        'PARKID': 'VARCHAR',
        'NAME': 'VARCHAR',
        'AKA': 'VARCHAR',
        'CITY': 'VARCHAR',
        'STATE': 'VARCHAR',
        'START': 'VARCHAR',
        '"END"': 'VARCHAR',
        'LEAGUE': 'VARCHAR',
        'NOTES': 'VARCHAR',
    }

    BATTING_FIELD_DTYPES = {
        'gid': 'VARCHAR',
        'id': 'VARCHAR',
        'team': 'VARCHAR',
        'b_lp': 'USMALLINT',
        'b_seq': 'USMALLINT',
        'stattype': 'VARCHAR',
        'b_pa': 'USMALLINT',
        'b_ab': 'USMALLINT',
        'b_r': 'USMALLINT',
        'b_h': 'USMALLINT',
        'b_d': 'USMALLINT',
        'b_t': 'USMALLINT',
        'b_hr': 'USMALLINT',
        'b_rbi': 'USMALLINT',
        'b_sh': 'USMALLINT',
        'b_sf': 'USMALLINT',
        'b_hbp': 'USMALLINT',
        'b_w': 'USMALLINT',
        'b_iw': 'USMALLINT',
        'b_k': 'USMALLINT',
        'b_sb': 'USMALLINT',
        'b_cs': 'USMALLINT',
        'b_gdp': 'USMALLINT',
        'b_xi': 'USMALLINT',
        'b_roe': 'USMALLINT',
        'dh': 'USMALLINT',
        'ph': 'USMALLINT',
        'pr': 'USMALLINT',
        'date': 'VARCHAR',
        'number': 'USMALLINT',
        'site': 'VARCHAR',
        'vishome': 'VARCHAR',
        'opp': 'VARCHAR',
        'win': 'USMALLINT',
        'loss': 'USMALLINT',
        'tie': 'USMALLINT',
        'gametype': 'VARCHAR',
        'box': 'VARCHAR',
        'pbp': 'VARCHAR'
    }

    DISCREPS_FIELD_DTYPES = {
        'ID': 'VARCHAR',
        'Player': 'VARCHAR',
        'Year': 'USMALLINT',
        'Team': 'VARCHAR',
        'Type': 'VARCHAR',
        'Pos': 'VARCHAR',
        'Cat': 'VARCHAR',
        'Game': 'VARCHAR',
        'Retro': 'USMALLINT',
        'Official': 'USMALLINT',
        '"Cross"': 'VARCHAR',
        'Code': 'VARCHAR',
        'X': 'VARCHAR',
        'Notes': 'VARCHAR',
        'Accepted': 'VARCHAR'
    }

    EJECTIONS_FIELD_DTYPES = {
        'GAMEID': 'VARCHAR',
        'DATE': 'VARCHAR',
        'DH': 'USMALLINT',
        'EJECTEE': 'VARCHAR',
        'EJECTEENAME': 'VARCHAR',
        'TEAM': 'VARCHAR',
        'JOB': 'VARCHAR',
        'UMPIRE': 'VARCHAR',
        'UMPIRENAME': 'VARCHAR',
        'INNING': 'SMALLINT',
        'REASON': 'VARCHAR',
    }

    FIELDING_FIELD_DTYPES = {
        'gid': 'VARCHAR',
        'id': 'VARCHAR',
        'team': 'VARCHAR',
        'd_seq': 'USMALLINT',
        'd_pos': 'VARCHAR',
        'stattype': 'VARCHAR',
        'd_ifouts': 'USMALLINT',
        'd_po': 'USMALLINT',
        'd_a': 'USMALLINT',
        'd_e': 'USMALLINT',
        'd_dp': 'USMALLINT',
        'd_tp': 'USMALLINT',
        'd_pb': 'USMALLINT',
        'd_wp': 'USMALLINT',
        'd_sb': 'USMALLINT',
        'd_cs': 'USMALLINT',
        'd_gs': 'USMALLINT',
        'date': 'VARCHAR',
        'number': 'USMALLINT',
        'site': 'VARCHAR',
        'vishome': 'VARCHAR',
        'opp': 'VARCHAR',
        'win': 'USMALLINT',
        'loss': 'USMALLINT',
        'tie': 'USMALLINT',
        'gametype': 'VARCHAR',
        'box': 'VARCHAR',
        'pbp': 'VARCHAR'
    }

    GAMEINFO_FIELD_DTYPES = {
        'gid': 'VARCHAR',
        'visteam': 'VARCHAR',
        'hometeam': 'VARCHAR',
        'site': 'VARCHAR',
        'date': 'VARCHAR',
        'number': 'USMALLINT',
        'starttime': 'VARCHAR',
        'daynight': 'VARCHAR',
        'innings': 'USMALLINT',
        'tiebreaker': 'USMALLINT',
        'usedh': 'BOOLEAN',
        'htbf': 'BOOLEAN',
        'timeofgame': 'VARCHAR',
        'attendance': 'VARCHAR',
        'fieldcond': 'VARCHAR',
        'precip': 'VARCHAR',
        'sky': 'VARCHAR',
        'temp': 'VARCHAR',
        'winddir': 'VARCHAR',
        'windspeed': 'VARCHAR',
        'oscorer': 'VARCHAR',
        'forfeit': 'VARCHAR',
        'suspend': 'VARCHAR',
        'umphome': 'VARCHAR',
        'ump1b': 'VARCHAR',
        'ump2b': 'VARCHAR',
        'ump3b': 'VARCHAR',
        'umplf': 'VARCHAR',
        'umprf': 'VARCHAR',
        'wp': 'VARCHAR',
        'lp': 'VARCHAR',
        'save': 'VARCHAR',
        'gametype': 'VARCHAR',
        'vruns': 'USMALLINT',
        'hruns': 'USMALLINT',
        'wteam': 'VARCHAR',
        'lteam': 'VARCHAR',
        'line': 'VARCHAR',
        'batteries': 'VARCHAR',
        'lineups': 'VARCHAR',
        'box': 'VARCHAR',
        'pbp': 'VARCHAR',
        'season': 'USMALLINT'
    }
    
    PITCHING_FIELD_DTYPES = {
        'gid': 'VARCHAR',
        'id': 'VARCHAR',
        'team': 'VARCHAR',
        'p_seq': 'USMALLINT',
        'stattype': 'VARCHAR',
        'p_ipouts': 'USMALLINT',
        'p_noout': 'USMALLINT',
        'p_bfp': 'USMALLINT',
        'p_h': 'USMALLINT',
        'p_d': 'USMALLINT',
        'p_t': 'USMALLINT',
        'p_hr': 'USMALLINT',
        'p_r': 'USMALLINT',
        'p_er': 'USMALLINT',
        'p_w': 'USMALLINT',
        'p_iw': 'USMALLINT',
        'p_k': 'USMALLINT',
        'p_hbp': 'USMALLINT',
        'p_wp': 'USMALLINT',
        'p_bk': 'USMALLINT',
        'p_sh': 'USMALLINT',
        'p_sf': 'USMALLINT',
        'p_sb': 'USMALLINT',
        'p_cs': 'USMALLINT',
        'p_pb': 'USMALLINT',
        'wp': 'USMALLINT',
        'lp': 'USMALLINT',
        'save': 'USMALLINT',
        'gs': 'USMALLINT',
        'gf': 'USMALLINT',
        'cg': 'USMALLINT',
        'date': 'VARCHAR',
        'number': 'USMALLINT',
        'site': 'VARCHAR',
        'vishome': 'VARCHAR',
        'opp': 'VARCHAR',
        'win': 'USMALLINT',
        'loss': 'USMALLINT',
        'tie': 'USMALLINT',
        'gametype': 'VARCHAR',
        'box': 'VARCHAR',
        'pbp': 'VARCHAR'

    }

    PLAYS_FIELD_DTYPES = {
        'gid': 'VARCHAR',
        'event': 'VARCHAR',
        'inning': 'VARCHAR',
        'top_bot': 'USMALLINT',
        'vis_home': 'USMALLINT',
        'site': 'VARCHAR',
        'batteam': 'VARCHAR',
        'pitteam': 'VARCHAR',
        'score_v': 'USMALLINT',
        'score_h': 'USMALLINT',
        'batter': 'VARCHAR',
        'pitcher': 'VARCHAR',
        'lp': 'USMALLINT',
        'bat_f': 'USMALLINT',
        'bathand': 'VARCHAR',
        'pithand': 'VARCHAR',
        'balls': 'VARCHAR',
        'strikes': 'VARCHAR',
        'count': 'VARCHAR',
        'pitches': 'VARCHAR',
        'nump': 'SMALLINT',
        'pa': 'USMALLINT',
        'ab': 'USMALLINT',
        'single': 'USMALLINT',
        'double': 'USMALLINT',
        'triple': 'USMALLINT',
        'hr': 'USMALLINT',
        'sh': 'USMALLINT',
        'sf': 'USMALLINT',
        'hbp': 'USMALLINT',
        'walk': 'USMALLINT',
        'k': 'USMALLINT',
        'xi': 'USMALLINT',
        'roe': 'USMALLINT',
        'fc': 'USMALLINT',
        'othout': 'USMALLINT',
        'noout': 'USMALLINT',
        'oth': 'USMALLINT',
        'bip': 'USMALLINT',
        'bunt': 'USMALLINT',
        'ground': 'USMALLINT',
        'fly': 'USMALLINT',
        'line': 'USMALLINT',
        'iw': 'USMALLINT',
        'gdp': 'USMALLINT',
        'othdp': 'USMALLINT',
        'tp': 'USMALLINT',
        'fle': 'USMALLINT',
        'wp': 'USMALLINT',
        'pb': 'USMALLINT',
        'bk': 'USMALLINT',
        'oa': 'USMALLINT',
        'di': 'USMALLINT',
        'sb2': 'USMALLINT',
        'sb3': 'USMALLINT',
        'sbh': 'USMALLINT',
        'cs2': 'USMALLINT',
        'cs3': 'USMALLINT',
        'csh': 'USMALLINT',
        'pko1': 'USMALLINT',
        'pko2': 'USMALLINT',
        'pko3': 'USMALLINT',
        'k_safe': 'USMALLINT',
        'e1': 'USMALLINT',
        'e2': 'USMALLINT',
        'e3': 'USMALLINT',
        'e4': 'USMALLINT',
        'e5': 'USMALLINT',
        'e6': 'USMALLINT',
        'e7': 'USMALLINT',
        'e8': 'USMALLINT',
        'e9': 'USMALLINT',
        'outs_pre': 'USMALLINT',
        'outs_post': 'USMALLINT',
        'br1_pre': 'VARCHAR',
        'br2_pre': 'VARCHAR',
        'br3_pre': 'VARCHAR',
        'br1_post': 'VARCHAR',
        'br2_post': 'VARCHAR',
        'br3_post': 'VARCHAR',
        'lob_id1': 'VARCHAR',
        'lob_id2': 'VARCHAR',
        'lob_id3': 'VARCHAR',
        'pr1_pre': 'VARCHAR',
        'pr2_pre': 'VARCHAR',
        'pr3_pre': 'VARCHAR',
        'pr1_post': 'VARCHAR',
        'pr2_post': 'VARCHAR',
        'pr3_post': 'VARCHAR',
        'run_b': 'VARCHAR',
        'run1': 'VARCHAR',
        'run2': 'VARCHAR',
        'run3': 'VARCHAR',
        'prun_b': 'VARCHAR',
        'prun1': 'VARCHAR',
        'prun2': 'VARCHAR',
        'prun3': 'VARCHAR',
        'ur_b': 'VARCHAR',
        'ur1': 'VARCHAR',
        'ur2': 'VARCHAR',
        'ur3': 'VARCHAR',
        'rbi_b': 'VARCHAR',
        'rbi1': 'VARCHAR',
        'rbi2': 'VARCHAR',
        'rbi3': 'VARCHAR',
        'runs': 'USMALLINT',
        'rbi': 'USMALLINT',
        'er': 'USMALLINT',
        'tur': 'USMALLINT',
        'l1': 'VARCHAR',
        'l2': 'VARCHAR',
        'l3': 'VARCHAR',
        'l4': 'VARCHAR',
        'l5': 'VARCHAR',
        'l6': 'VARCHAR',
        'l7': 'VARCHAR',
        'l8': 'VARCHAR',
        'l9': 'VARCHAR',
        'lf1': 'USMALLINT',
        'lf2': 'USMALLINT',
        'lf3': 'USMALLINT',
        'lf4': 'USMALLINT',
        'lf5': 'USMALLINT',
        'lf6': 'USMALLINT',
        'lf7': 'USMALLINT',
        'lf8': 'USMALLINT',
        'lf9': 'USMALLINT',
        'f2': 'VARCHAR',
        'f3': 'VARCHAR',
        'f4': 'VARCHAR',
        'f5': 'VARCHAR',
        'f6': 'VARCHAR',
        'f7': 'VARCHAR',
        'f8': 'VARCHAR',
        'f9': 'VARCHAR',
        'po0': 'USMALLINT',
        'po1': 'USMALLINT',
        'po2': 'USMALLINT',
        'po3': 'USMALLINT',
        'po4': 'USMALLINT',
        'po5': 'USMALLINT',
        'po6': 'USMALLINT',
        'po7': 'USMALLINT',
        'po8': 'USMALLINT',
        'po9': 'USMALLINT',
        'a1': 'USMALLINT',
        'a2': 'USMALLINT',
        'a3': 'USMALLINT',
        'a4': 'USMALLINT',
        'a5': 'USMALLINT',
        'a6': 'USMALLINT',
        'a7': 'USMALLINT',
        'a8': 'USMALLINT',
        'a9': 'USMALLINT',
        'fseq': 'VARCHAR',
        'batout1': 'USMALLINT',
        'batout2': 'USMALLINT',
        'batout3': 'USMALLINT',
        'brout_b': 'USMALLINT',
        'brout1': 'USMALLINT',
        'brout2': 'USMALLINT',
        'brout3': 'USMALLINT',
        'firstf': 'USMALLINT',
        'loc': 'VARCHAR',
        'hittype': 'VARCHAR',
        'dpopp': 'USMALLINT',
        '"pivot"': 'VARCHAR',
        'pn': 'USMALLINT',
        'umphome': 'VARCHAR',
        'ump1b': 'VARCHAR',
        'ump2b': 'VARCHAR',
        'ump3b': 'VARCHAR',
        'umplf': 'VARCHAR',
        'umprf': 'VARCHAR',
        'date': 'VARCHAR',
        'gametype': 'VARCHAR',
        'pbp': 'VARCHAR'
    }

    TEAMS_FIELD_DTYPES = {
        'TEAM': 'VARCHAR',
        'LEAGUE': 'VARCHAR',
        'CITY': 'VARCHAR',
        'NICKNAME': 'VARCHAR',
        'FIRST': 'INTEGER',
        'LAST': 'INTEGER',
    }

    TEAMSTATS_FIELD_DTYPES = {
        'gid': 'VARCHAR',
        'team': 'VARCHAR',
        'inn1': 'VARCHAR',
        'inn2': 'VARCHAR',
        'inn3': 'VARCHAR',
        'inn4': 'VARCHAR',
        'inn5': 'VARCHAR',
        'inn6': 'VARCHAR',
        'inn7': 'VARCHAR',
        'inn8': 'VARCHAR',
        'inn9': 'VARCHAR',
        'inn10': 'VARCHAR',
        'inn11': 'VARCHAR',
        'inn12': 'VARCHAR',
        'inn13': 'VARCHAR',
        'inn14': 'VARCHAR',
        'inn15': 'VARCHAR',
        'inn16': 'VARCHAR',
        'inn17': 'VARCHAR',
        'inn18': 'VARCHAR',
        'inn19': 'VARCHAR',
        'inn20': 'VARCHAR',
        'inn21': 'VARCHAR',
        'inn22': 'VARCHAR',
        'inn23': 'VARCHAR',
        'inn24': 'VARCHAR',
        'inn25': 'VARCHAR',
        'inn26': 'VARCHAR',
        'inn27': 'VARCHAR',
        'inn28': 'VARCHAR',
        'lob': 'SMALLINT',
        'mgr': 'VARCHAR',
        'stattype': 'VARCHAR',
        'b_pa': 'USMALLINT',
        'b_ab': 'USMALLINT',
        'b_r': 'USMALLINT',
        'b_h': 'USMALLINT',
        'b_d': 'USMALLINT',
        'b_t': 'USMALLINT',
        'b_hr': 'USMALLINT',
        'b_rbi': 'USMALLINT',
        'b_sh': 'USMALLINT',
        'b_sf': 'USMALLINT',
        'b_hbp': 'USMALLINT',
        'b_w': 'VARCHAR',
        'b_iw': 'USMALLINT',
        'b_k': 'VARCHAR',
        'b_sb': 'USMALLINT',
        'b_cs': 'USMALLINT',
        'b_gdp': 'USMALLINT',
        'b_xi': 'USMALLINT',
        'b_roe': 'USMALLINT',
        'p_ipouts': 'USMALLINT',
        'p_noout': 'USMALLINT',
        'p_bfp': 'USMALLINT',
        'p_h': 'USMALLINT',
        'p_d': 'USMALLINT',
        'p_t': 'USMALLINT',
        'p_hr': 'USMALLINT',
        'p_r': 'USMALLINT',
        'p_er': 'USMALLINT',
        'p_w': 'VARCHAR',
        'p_iw': 'USMALLINT',
        'p_k': 'VARCHAR',
        'p_hbp': 'USMALLINT',
        'p_wp': 'USMALLINT',
        'p_bk': 'USMALLINT',
        'p_sh': 'USMALLINT',
        'p_sf': 'USMALLINT',
        'p_sb': 'USMALLINT',
        'p_cs': 'USMALLINT',
        'p_pb': 'USMALLINT',
        'd_po': 'USMALLINT',
        'd_a': 'USMALLINT',
        'd_e': 'USMALLINT',
        'd_dp': 'USMALLINT',
        'd_tp': 'USMALLINT',
        'd_pb': 'USMALLINT',
        'd_wp': 'USMALLINT',
        'd_sb': 'USMALLINT',
        'd_cs': 'USMALLINT',
        'start_l1': 'VARCHAR',
        'start_l2': 'VARCHAR',
        'start_l3': 'VARCHAR',
        'start_l4': 'VARCHAR',
        'start_l5': 'VARCHAR',
        'start_l6': 'VARCHAR',
        'start_l7': 'VARCHAR',
        'start_l8': 'VARCHAR',
        'start_l9': 'VARCHAR',
        'start_f1': 'VARCHAR',
        'start_f2': 'VARCHAR',
        'start_f3': 'VARCHAR',
        'start_f4': 'VARCHAR',
        'start_f5': 'VARCHAR',
        'start_f6': 'VARCHAR',
        'start_f7': 'VARCHAR',
        'start_f8': 'VARCHAR',
        'start_f9': 'VARCHAR',
        'start_f10': 'VARCHAR',
        'date': 'VARCHAR',
        'number': 'USMALLINT',
        'site': 'VARCHAR',
        'vishome': 'VARCHAR',
        'opp': 'VARCHAR',
        'win': 'USMALLINT',
        'loss': 'USMALLINT',
        'tie': 'USMALLINT',
        'gametype': 'VARCHAR',
        'box': 'VARCHAR',
        'pbp': 'VARCHAR'
    }

    def __init__(self, data_dir = 'data') -> None:
        self.data_dir = Path(data_dir) / 'retrosheet'
        self.data_dir.mkdir(parents=True, exist_ok=True)

    def download(self, file: str = 'csvdownloads') -> None:
        """Download Retrosheet files."""
        if file not in ('ballparks', 'csvdownloads', 'teams'):
            raise Exception('Not a valid file.')
        
        if file == 'csvdownloads':
            url = 'https://www.retrosheet.org/downloads/csvdownloads.zip'
        else:
            url = f'https://www.retrosheet.org/{file}.zip'
        
        resp = requests.get(url)

        filepath = self.data_dir / f'{file}.zip'
        with open(filepath, 'wb') as f:
            f.write(resp.content)

    def unzip(self, file: str = 'csvdownloads') -> None:
        """Unzip Retrosheet files."""
        if file not in ('ballparks', 'csvdownloads', 'teams'):
            raise Exception('Not a valid file.')

        filepath = self.data_dir / f'{file}.zip'
        with ZipFile(filepath, 'r') as zf:
            zf.extractall(self.data_dir)

    def cleanup(self) -> None:
        """Removes downloaded zip files."""
        zipfiles = self.data_dir.glob('*.zip')
        for file in zipfiles:
            file.unlink()

    def load(self, data_model: str) -> None:
        """Load Retrosheet data into database."""
        if data_model not in (
            'allplayers',
            'ballparks',
            'batting',
            'discreps',
            'ejections',
            'fielding',
            'gameinfo',
            'pitching',
            'plays',
            'teams',
            'teamstats'
        ):
            raise Exception('Not a valid data model.')

        filepath = self.data_dir / f'{data_model}.csv'

        field_dtypes_map = {
            'allplayers': self.ALLPLAYERS_FIELD_DTYPES,
            'ballparks': self.BALLPARKS_FIELD_DTYPES,
            'batting': self.BATTING_FIELD_DTYPES,
            'discreps': self.DISCREPS_FIELD_DTYPES,
            'ejections': self.EJECTIONS_FIELD_DTYPES,
            'fielding': self.FIELDING_FIELD_DTYPES,
            'gameinfo': self.GAMEINFO_FIELD_DTYPES,
            'pitching': self.PITCHING_FIELD_DTYPES,
            'plays': self.PLAYS_FIELD_DTYPES,
            'teams': self.TEAMS_FIELD_DTYPES,
            'teamstats': self.TEAMSTATS_FIELD_DTYPES
        }
        field_dtypes = field_dtypes_map[data_model]

        fields_sql = ",\n".join(" ".join(i) for i in field_dtypes.items())

        sql = f"""
            CREATE OR REPLACE TABLE raw.retrosheet_{data_model} ({fields_sql});
            COPY raw.retrosheet_{data_model} FROM '{filepath}' (HEADER);
        """
        con = duckdb.connect(DATABASE_NAME)
        con.execute(sql)
        con.close()

    def extract_load_all(self) -> None:
        """Download files and upload to database."""
        for file in ['ballparks', 'csvdownloads', 'teams']:
            self.download(file)
            self.unzip(file)

        self.cleanup()

        for data_model in [
            'allplayers',
            'batting',
            'discreps',
            'ejections',
            'fielding',
            'gameinfo',
            'pitching',
            'plays',
            'teamstats'
        ]:
            self.load(data_model)
